import Header from '@/components/layout/header';
import Sidebar from '@/components/layout/sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';
import type { Metadata } from 'next';
import { Plus_Jakarta_Sans } from 'next/font/google';
import './globals.css';
import StoreProvider from '@/redux/StoreProvider';
import MenuSelector from '@/components/menuselector';

const jakartaSans = Plus_Jakarta_Sans({
  variable: '--font-jakarta-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakartaSans.variable} antialiased`}>
        <StoreProvider>
          <SidebarProvider>
            <Sidebar />
            <main className="w-full px-14">
              <Header />
              <MenuSelector />
              {children}
            </main>
          </SidebarProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
