import { ApiProperty } from '@nestjs/swagger';

export class CreateMenu {
  @ApiProperty({
    description: 'Menu Id, generated by uuid',
    nullable: false,
    required: true,
    type: 'string',
    example: 'cm59fkd2d000012vo680nsvh6',
  })
  id: string;

  @ApiProperty({
    description: 'Menu Name',
    nullable: false,
    required: true,
    type: 'string',
    example: 'System',
  })
  name: string;
}
