import { ApiProperty } from '@nestjs/swagger';

export class Item {
  @ApiProperty({
    description: 'Menu Id, generated by uuid',
    nullable: false,
    required: true,
    type: 'string',
    example: 'cm59fkd2d000012vo680nsvh6',
  })
  id: string;

  @ApiProperty({
    description: 'Menu Name',
    nullable: false,
    required: true,
    type: 'string',
    example: 'System',
  })
  name: string;

  @ApiProperty({
    description: 'Children items in the menu',
    nullable: true,
    required: false,
    type: [Item],
    example: [
      {
        id: 'cm59fo8r2000812vo5e5zh06j',
        name: 'Cheeseburger',
        depth: 1,
        menu_id: 'cm59fkd2d000012vo680nsvh6',
        parent_id: 'cm59fkd2d000012vo680nsvh6',
        children: [
          {
            id: 'cm59fofnm000a12vokfqaqg2r',
            name: 'Cheeseburger 2',
            depth: 2,
            menu_id: 'cm59fkd2d000012vo680nsvh6',
            parent_id: 'cm59fo8r2000812vo5e5zh06j',
            children: [
              {
                id: 'cm59fomca000c12vohsqwtfj0',
                name: 'Cheeseburger 2',
                depth: 3,
                menu_id: 'cm59fkd2d000012vo680nsvh6',
                parent_id: 'cm59fofnm000a12vokfqaqg2r',
                children: [],
              },
            ],
          },
        ],
      },
    ],
  })
  children?: Item[];
}
